services:
  - docker

language: go

stages:
  - docker-build
  - docker-publish
#  - name: deploy
#    if: branch = master

jobs:
  include:
    - stage: docker-build
      script: make docker-build
    - stage: docker-publish
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker-publish